name: Build

on:
  push:
    branches:
      - '*'

env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isFinalRelease: ${{ contains(github.ref, 'master') }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup APT repositories for ARM
      run: sudo mv sources.list /etc/apt/sources.list

    - name: Add ARM architecture to APT
      run: sudo dpkg --add-architecture armhf

    - name: Update APT repositories
      run: sudo apt update
    
    - name: Download toolchain for ARM
      run: sudo curl -o /opt/toolchain.tar.bz2  https://toolchains.bootlin.com/downloads/releases/toolchains/armv5-eabi/tarballs/armv5-eabi--uclibc--stable-2022.08-1.tar.bz2
    - name: Install uClibc ARM cross compiler
      run: sudo mkdir /opt/toolchain && sudo tar jxf /opt/toolchain.tar.bz2 -C /opt/toolchain --strip-components=1

    - name: Install dependencies
      run: sudo apt install -y build-essential flex bison byacc make m4 openssl:armhf libssl-dev:armhf liblz-dev:armhf liblz-dev zlib1g-dev:armhf

    - name: Compile
      run: make distclean && sudo make release ARMCXX=/opt/toolchain/bin/arm-buildroot-linux-uclibcgnueabi-c++

    - name: Release Candidate
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isNightly == 'true'
      with:
        automatic_release_tag: latest-rc
        files: onvif_srvd
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: latest-rc

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isFinalRelease == 'true'
      with:
        automatic_release_tag: stable
        files: onvif_srvd
        prerelease: false
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: stable
